################## MAIN ###
GET http://localhost:3000 HTTP/1.1
###
GET http://localhost:3000/broken.html HTTP/1.1
###
GET http://localhost:3000/broken.cgi HTTP/1.1
###
GET http://localhost:3000/aboutus.html HTTP/1.1
###
################## CAMPSITES ###
POST http://localhost:3000/campsites HTTP/1.1
Content-Type: application/json

{
    "name": "sample",
    "description": "Wed, 21 Oct 2023 18:34:34 GMT"
}

###
GET http://localhost:3000/campsites
###
GET http://localhost:3000/campsites/23
###
DELETE http://localhost:3000/campsites/23
################## PROMOTIONS ###
GET http://localhost:3000/promotions
###
GET http://localhost:3000/promotions/23
###
DELETE http://localhost:3000/promotions/23
################## PARTNERS ###
GET http://localhost:3000/partners
###
GET http://localhost:3000/partners/23
###
DELETE http://localhost:3000/partners/23
###
DELETE http://localhost:3000/partners
